# Generated by Django 2.1.2 on 2019-11-25 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
        ('Places', '0002_places_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelLouge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='بدون عنوان', max_length=102)),
                ('description', models.TextField(default='بدون توضیحات')),
                ('image1', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, upload_to='image/%Y/%m/%d/')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Leader')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.Places')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
