# Generated by Django 2.2.1 on 2019-10-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='بدون عنوان', max_length=102)),
                ('Description', models.TextField(default='بدون توضیحات')),
                ('Likes', models.CharField(default='0', max_length=1, null=True)),
                ('categories', models.CharField(choices=[('Historical', 'Historical'), ('museums', 'museums'), ('Forests', 'Forests'), ('Public art', 'Public art'), ('national parks', 'national parks')], default='museums', max_length=200)),
                ('Hardness', models.CharField(default='بدون درجه ی سختی', max_length=102)),
                ('Address', models.CharField(default='بدون آدرس ', max_length=102)),
                ('Time', models.CharField(default='بدون  تخمین زمان ', max_length=102)),
                ('City', models.CharField(default='بدون شهر', max_length=102)),
                ('Average', models.CharField(default='0', max_length=102)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.Places')),
            ],
        ),
    ]
