# Generated by Django 2.2.1 on 2019-10-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='EndTime',
            field=models.CharField(default='بدون زمان پایان ', max_length=102),
        ),
        migrations.AddField(
            model_name='places',
            name='StartTime',
            field=models.CharField(default='بدون زمان شروع ', max_length=102),
        ),
    ]
