# Generated by Django 2.2.1 on 2019-10-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_auto_20191025_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='categories',
            field=models.CharField(choices=[('تاریخی', 'تاریخی'), ('موزه', 'موزه'), ('جنگل', 'جنگل'), ('کوه', 'کوه'), ('طبیعت', 'طبیعت'), ('پارک ملی', 'پارک ملی'), ('هنر عمومی', 'هنر عمومی'), ('مذهبی', 'مذهبی')], default='موزه', max_length=200),
        ),
    ]
