# Generated by Django 2.2.1 on 2019-10-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0003_auto_20191025_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='image1',
            field=models.ImageField(blank=True, upload_to='C:\\SE_Project_DjangoRest98\\media'),
        ),
        migrations.AddField(
            model_name='places',
            name='image2',
            field=models.ImageField(blank=True, upload_to='C:\\SE_Project_DjangoRest98\\media'),
        ),
        migrations.AddField(
            model_name='places',
            name='image3',
            field=models.ImageField(blank=True, upload_to='C:\\SE_Project_DjangoRest98\\media'),
        ),
        migrations.DeleteModel(
            name='PlaceImage',
        ),
    ]
