# Generated by Django 2.1.2 on 2019-12-26 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0004_auto_20191226_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='place',
        ),
        migrations.AddField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Places.Places'),
        ),
    ]
