# Generated by Django 2.1.2 on 2019-11-06 15:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalID', models.IntegerField()),
                ('has_car', models.BooleanField(default=False)),
                ('car_capacity', models.IntegerField()),
                ('car_model', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('itinerary', models.CharField(max_length=500)),
                ('is_leader', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='leader',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
        ),
    ]
