# Generated by Django 2.2.2 on 2019-10-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
