# Generated by Django 2.2.2 on 2019-11-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='age',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='leader',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/profile/profile.jpg', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='car_capacity',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='leader',
            name='nationalID',
            field=models.CharField(max_length=12),
        ),
    ]
