# Generated by Django 2.2.2 on 2019-11-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
