# Generated by Django 2.2.2 on 2019-12-26 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_leader_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.Leader')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
