# Generated by Django 2.2.2 on 2019-10-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leader',
            old_name='user',
            new_name='userID',
        ),
    ]
