# Generated by Django 2.2.2 on 2019-11-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20191016_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='car_capacity',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='leader',
            name='nationalID',
            field=models.CharField(max_length=12),
        ),
    ]
