# Generated by Django 2.2.2 on 2019-12-26 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20191227_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderrate',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Leader'),
        ),
    ]
