# Generated by Django 2.2.2 on 2019-11-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20191107_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/profile.jpg', height_field=100, upload_to='media/image/profile', width_field=100),
        ),
    ]
