# Generated by Django 2.2.2 on 2020-01-27 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20191227_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOBJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='leader',
            name='freetimes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.TimeOBJ'),
        ),
    ]
