# Generated by Django 2.2.2 on 2019-11-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_auto_20191108_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static/profile/profile.jpg', upload_to='media/image/profile'),
        ),
    ]
