# Generated by Django 2.2.2 on 2019-11-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20191108_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='leader',
            name='gender',
            field=models.BooleanField(default=None),
        ),
    ]
