# Generated by Django 2.2.2 on 2019-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_auto_20191108_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leader',
            name='gender',
            field=models.BooleanField(default=0),
        ),
    ]
