# Generated by Django 2.2.2 on 2019-11-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_auto_20191108_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='age',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='gender',
        ),
    ]
