# Generated by Django 2.2.2 on 2019-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_auto_20191108_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='age',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='leader',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
