# Generated by Django 2.1.2 on 2019-12-16 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseService', '0002_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelLouge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=102)),
                ('description', models.CharField(max_length=1000)),
                ('image1', models.ImageField(default='travellouge/defualt.jpg', upload_to='image/%Y/%m/%d/')),
                ('image2', models.ImageField(default='travellouge/defualt.jpg', upload_to='image/%Y/%m/%d/')),
                ('image3', models.ImageField(default='travellouge/defualt.jpg', upload_to='image/%Y/%m/%d/')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travellouge_author', to='DatabaseService.users')),
                ('places', models.ManyToManyField(related_name='place_travellogue', to='DatabaseService.Places')),
            ],
        ),
    ]
