# Generated by Django 2.1.2 on 2019-12-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseService', '0005_auto_20191216_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellouges',
            name='places',
            field=models.ManyToManyField(related_name='visitedplaces_travellogue', to='DatabaseService.Places'),
        ),
    ]
