# Generated by Django 2.1.2 on 2019-12-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseService', '0006_auto_20191216_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travellouges',
            old_name='places',
            new_name='place',
        ),
    ]
