# Generated by Django 2.1.2 on 2019-12-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseService', '0003_travellouge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellouge',
            name='places',
            field=models.ManyToManyField(related_name='place_travelloguess', to='DatabaseService.Places'),
        ),
    ]
