# Generated by Django 2.1.2 on 2019-12-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_places_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='categories',
            field=models.CharField(choices=[('historical', 'historical'), ('موزه', 'موزه'), ('جنگل', 'جنگل'), ('کوه', 'کوه'), ('طبیعت', 'طبیعت'), ('پارک ملی', 'پارک ملی'), ('هنر عمومی', 'هنر عمومی'), ('مذهبی', 'مذهبی')], default='موزه', max_length=200),
        ),
    ]
