# Generated by Django 2.1.2 on 2019-12-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0003_auto_20191219_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='categories',
            field=models.CharField(choices=[('تاریخی', 'تاریخی'), ('موزه', 'موزه'), ('جنگل', 'جنگل'), ('کوه', 'کوه'), ('طبیعت', 'طبیعت'), ('پارک ملی', 'پارک ملی'), ('هنر عمومی', 'هنر عمومی'), ('مذهبی', 'مذهبی')], default='موزه', max_length=200),
        ),
    ]
