# Generated by Django 2.2.2 on 2020-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0004_auto_20191219_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='Address',
            field=models.CharField(blank=True, default='بدون آدرس ', max_length=102),
        ),
        migrations.AlterField(
            model_name='places',
            name='Average',
            field=models.CharField(blank=True, default='0', max_length=102),
        ),
        migrations.AlterField(
            model_name='places',
            name='City',
            field=models.CharField(blank=True, default='بدون شهر', max_length=102),
        ),
        migrations.AlterField(
            model_name='places',
            name='Description',
            field=models.TextField(blank=True, default='بدون توضیحات'),
        ),
        migrations.AlterField(
            model_name='places',
            name='EndTime',
            field=models.CharField(blank=True, default='بدون زمان پایان ', max_length=102),
        ),
        migrations.AlterField(
            model_name='places',
            name='Hardness',
            field=models.CharField(blank=True, default='بدون درجه ی سختی', max_length=102),
        ),
        migrations.AlterField(
            model_name='places',
            name='Likes',
            field=models.CharField(blank=True, default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='StartTime',
            field=models.CharField(blank=True, default='بدون زمان شروع ', max_length=102),
        ),
        migrations.AlterField(
            model_name='places',
            name='Time',
            field=models.CharField(blank=True, default='بدون  تخمین زمان ', max_length=102),
        ),
        migrations.AlterField(
            model_name='places',
            name='categories',
            field=models.CharField(blank=True, choices=[('تاریخی', 'تاریخی'), ('موزه', 'موزه'), ('جنگل', 'جنگل'), ('کوه', 'کوه'), ('طبیعت', 'طبیعت'), ('پارک ملی', 'پارک ملی'), ('هنر عمومی', 'هنر عمومی'), ('مذهبی', 'مذهبی')], default='موزه', max_length=200),
        ),
    ]
