# Generated by Django 2.1.2 on 2019-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='leader',
            field=models.ManyToManyField(to='Users.Leader'),
        ),
    ]
